---
- name: Install Vim and plugin dependancies
  pacman:
    name:
      - base-devel
      - cmake
      - go
      - jre-openjdk
      - python
      - python-pip
      - vim
      - npm
  become: yes

- name: Install Python dependancies
  pip:
    name:
      - black
      - flake8
      - isort
    extra_args: --user
