---
- name: Install Vim and plugin dependancies (MacOS 12.3.1)
  community.general.homebrew:
    name:
      - cmake
      - go
      - python3
      - vim
      - npm
    state: present

- name: Install plugin dependancies (cask) (MacOS 12.3.1)
  community.general.homebrew_cask:
    name:
      - oracle-jdk
    state: present
