---
- name: Install Vim and plugin dependancies (MacOS 12.3.1)
  community.general.homebrew:
    name:
      - cmake
      - go
      - python3
      - vim
      - npm
      - homebrew/cask/oracle-jdk
    state: present
