---
- name: Create .vim directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.vim"
    state: directory

- name: Create plugged directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.vim/plugged"
    state: directory

- name: Install vim configuration
  ansible.builtin.copy:
    src: vimrc
    dest: "/home/{{ username }}/.vim/vimrc"
    force: yes

- name: Install flake8 configuration
  ansible.builtin.copy:
    src: flake8
    dest: "/home/{{ username }}/.config/flake8"
    force: yes

- name: Symlink vim configuration
  ansible.builtin.file:
    src: "/home/{{ username }}/.vim/vimrc"
    dest: "/home/{{ username }}/.vimrc"
    state: link
