---
- name: Create .vim directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory

- name: Create plugged directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/plugged"
    state: directory

- name: Install vim configuration
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vim/vimrc"
    force: yes

- name: Install flake8 configuration
  ansible.builtin.copy:
    src: flake8
    dest: "{{ ansible_env.HOME }}/.config/flake8"
    force: yes

- name: Symlink vim configuration
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.vim/vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
